social_flex.settings:
  type: config_object
  label: 'Social Flex Settings'
  mapping:
    flexible_group_types:
      type: sequence
      label: 'For which group type the social flex feature is turned on.'
      group_type:
        type: string
        label: 'Group Type'
